#!/usr/bin/env bash
set -euo pipefail

if [[ ${EUID} -ne 0 ]]; then echo "Run as root: sudo ./install.sh" >&2; exit 1; fi
ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
APP_DIR=/opt/focusguard
VENV_DIR=$APP_DIR/.venv
BIN_DIR=/usr/local/bin
need=(python3 systemctl nft nmcli dnsmasq)
missing=()
for cmd in "${need[@]}"; do command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd"); done
# Ensure pip is available for the isolated application environment.
if ! python3 -m pip --version >/dev/null 2>&1; then
  missing+=("pip")
fi
if ! python3 -m venv --help >/dev/null 2>&1; then
  missing+=("venv")
fi
if ((${#missing[@]})); then
  if command -v pacman >/dev/null 2>&1; then
    pacman -S --needed --noconfirm python nftables networkmanager dnsmasq python-pip
  else
    echo "Missing dependencies: ${missing[*]}. Install Python 3.13+ with pip and venv support, nftables, systemd, NetworkManager, and dnsmasq." >&2; exit 1
  fi
fi
python3 - <<'PY'
import sys
if sys.version_info < (3, 13):
    raise SystemExit('FocusGuard requires Python 3.13+')
PY
install -d "$APP_DIR" "$BIN_DIR" /etc/focusguard /etc/systemd/system /etc/NetworkManager/dispatcher.d /etc/NetworkManager/dnsmasq.d /etc/nftables.d /var/lib/focusguard /var/log/focusguard /etc/logrotate.d
rm -rf "$APP_DIR/src"
cp -a "$ROOT_DIR/src" "$ROOT_DIR/pyproject.toml" "$ROOT_DIR/README.md" "$ROOT_DIR/LICENSE" "$APP_DIR/"
python3 -m venv --clear "$VENV_DIR"
"$VENV_DIR/bin/python" -m pip install --upgrade "$APP_DIR"
# Remove launchers generated by older system-pip installs, but leave package-owned files alone.
for exe in focusguard focusguard-daemon focusguard-nm-dispatcher; do
  legacy="/usr/bin/$exe"
  if [[ -f "$legacy" && ! -L "$legacy" ]] \
    && { ! command -v pacman >/dev/null 2>&1 || ! pacman -Qo "$legacy" >/dev/null 2>&1; } \
    && grep -Fq "from focusguard." "$legacy" \
    && grep -Fq "sys.argv[0]" "$legacy"; then
    rm -f "$legacy"
  fi
done
# Keep the CLI and support entry points on PATH without modifying system Python.
for exe in focusguard focusguard-daemon focusguard-nm-dispatcher; do
  ln -sfn "$VENV_DIR/bin/$exe" "$BIN_DIR/$exe"
done

if [[ ! -f /etc/focusguard/config.toml ]]; then install -m 0644 "$ROOT_DIR/config/config.toml" /etc/focusguard/config.toml; fi
# Remove any stale unit (from prior versions) that may reference /run/focusguard causing ns mount failures
rm -f /etc/systemd/system/focusguard.service
rm -rf /run/focusguard 2>/dev/null || true
install -m 0644 "$ROOT_DIR/systemd/focusguard.service" /etc/systemd/system/focusguard.service
install -m 0644 "$ROOT_DIR/systemd/focusguard-logrotate" /etc/logrotate.d/focusguard
install -m 0755 "$ROOT_DIR/scripts/focusguard-nm-dispatcher" /etc/NetworkManager/dispatcher.d/90-focusguard
if ! grep -q '^dns=dnsmasq' /etc/NetworkManager/NetworkManager.conf 2>/dev/null; then
  install -d /etc/NetworkManager/conf.d
  printf '[main]\ndns=dnsmasq\n' >/etc/NetworkManager/conf.d/90-focusguard-dnsmasq.conf
fi
systemctl daemon-reload
systemctl enable --now nftables NetworkManager || true
systemctl enable focusguard
systemctl restart focusguard
# Give the daemon a moment to start (it may restart NM on first run)
for _ in 1 2 3 4 5; do
  if systemctl is-active --quiet focusguard; then break; fi
  sleep 1
done
if ! systemctl is-active --quiet focusguard; then
  echo "FocusGuard service did not become active. Recent logs:" >&2
  journalctl -u focusguard -n 50 --no-pager >&2 || true
  exit 1
fi
echo "FocusGuard installed. Edit /etc/focusguard/config.toml and run: sudo systemctl restart focusguard"
