import unittest.mock as mock
from datetime import datetime

import focusguard.cli as cli
from focusguard.cli import main


def test_version(capsys):
    assert main(["version"]) == 0
    assert "FocusGuard" in capsys.readouterr().out


def test_status_reports_active_enforcement(tmp_path, monkeypatch, capsys):
    config_path = tmp_path / "config.toml"
    config_path.write_text('blocklist = ["reddit.com"]\nwhitelist = []\n')
    dnsmasq_path = tmp_path / "focusguard.conf"
    dnsmasq_path.write_text("nftset=/reddit.com/4#inet#focusguard#blocked_v4\n")
    monkeypatch.setattr(cli, "CONFIG_PATH", config_path)
    monkeypatch.setattr(cli, "DNSMASQ_CONF", dnsmasq_path)
    monkeypatch.setattr(cli, "local_now", lambda: datetime(2026, 1, 1, 23))
    monkeypatch.setattr(cli, "service_active", lambda: True)
    monkeypatch.setattr(
        cli.subprocess,
        "run",
        mock.Mock(
            return_value=mock.Mock(
                returncode=0,
                stdout="table inet focusguard\n",
            )
        ),
    )

    assert main(["status"]) == 0
    assert "Enforcement: active" in capsys.readouterr().out


def test_status_reports_enforcement_mismatch(tmp_path, monkeypatch, capsys):
    config_path = tmp_path / "config.toml"
    config_path.write_text('blocklist = ["reddit.com"]\nwhitelist = []\n')
    dnsmasq_path = tmp_path / "focusguard.conf"
    dnsmasq_path.write_text("nftset=/reddit.com/4#inet#focusguard#blocked_v4\n")
    monkeypatch.setattr(cli, "CONFIG_PATH", config_path)
    monkeypatch.setattr(cli, "DNSMASQ_CONF", dnsmasq_path)
    monkeypatch.setattr(cli, "local_now", lambda: datetime(2026, 1, 1, 16))
    monkeypatch.setattr(cli, "service_active", lambda: True)
    monkeypatch.setattr(
        cli.subprocess,
        "run",
        mock.Mock(
            return_value=mock.Mock(
                returncode=0,
                stdout="table inet focusguard\n",
            )
        ),
    )

    assert main(["status"]) == 0
    assert "Enforcement: mismatch" in capsys.readouterr().out


def test_status_reports_clear_enforcement(tmp_path, monkeypatch, capsys):
    config_path = tmp_path / "config.toml"
    config_path.write_text('blocklist = ["reddit.com"]\nwhitelist = []\n')
    dnsmasq_path = tmp_path / "focusguard.conf"
    dnsmasq_path.write_text("# Generated by FocusGuard\n")
    monkeypatch.setattr(cli, "CONFIG_PATH", config_path)
    monkeypatch.setattr(cli, "DNSMASQ_CONF", dnsmasq_path)
    monkeypatch.setattr(cli, "local_now", lambda: datetime(2026, 1, 1, 16))
    monkeypatch.setattr(cli, "service_active", lambda: True)
    monkeypatch.setattr(
        cli.subprocess,
        "run",
        mock.Mock(return_value=mock.Mock(returncode=0, stdout="table inet other\n")),
    )

    assert main(["status"]) == 0
    assert "Enforcement: clear" in capsys.readouterr().out


def test_status_reports_unknown_enforcement_when_nft_is_unavailable(
    tmp_path, monkeypatch, capsys
):
    config_path = tmp_path / "config.toml"
    config_path.write_text('blocklist = ["reddit.com"]\nwhitelist = []\n')
    dnsmasq_path = tmp_path / "focusguard.conf"
    dnsmasq_path.write_text("nftset=/reddit.com/4#inet#focusguard#blocked_v4\n")
    monkeypatch.setattr(cli, "CONFIG_PATH", config_path)
    monkeypatch.setattr(cli, "DNSMASQ_CONF", dnsmasq_path)
    monkeypatch.setattr(cli, "local_now", lambda: datetime(2026, 1, 1, 23))
    monkeypatch.setattr(cli, "service_active", lambda: True)
    monkeypatch.setattr(
        cli.subprocess,
        "run",
        mock.Mock(return_value=mock.Mock(returncode=1, stdout="")),
    )

    assert main(["status"]) == 0
    assert "Enforcement: unknown" in capsys.readouterr().out


def test_logs_reports_disabled_logging(tmp_path, monkeypatch, capsys):
    config_path = tmp_path / "config.toml"
    config_path.write_text("logging = false\n")
    monkeypatch.setattr(cli, "CONFIG_PATH", config_path)

    assert main(["logs"]) == 0
    assert "Persistent logging is disabled" in capsys.readouterr().out


def test_reload_rejects_invalid_config(tmp_path, monkeypatch, capsys):
    config_path = tmp_path / "config.toml"
    config_path.write_text("unknown = true\n")
    monkeypatch.setattr(cli, "CONFIG_PATH", config_path)
    run = mock.Mock()
    monkeypatch.setattr(cli.subprocess, "run", run)

    assert main(["reload"]) == 2
    assert "Configuration error" in capsys.readouterr().err
    run.assert_not_called()


def test_reload_validates_config_before_reloading(tmp_path, monkeypatch):
    config_path = tmp_path / "config.toml"
    config_path.write_text("logging = false\n")
    monkeypatch.setattr(cli, "CONFIG_PATH", config_path)
    run = mock.Mock(return_value=mock.Mock(returncode=0))
    monkeypatch.setattr(cli.subprocess, "run", run)

    assert main(["reload"]) == 0
    run.assert_called_once_with(
        ["systemctl", "reload-or-restart", "focusguard"], check=False
    )
