"""Tests for nft/dnsmasq rule generation used in focus blocking enforcement."""

import tempfile
from datetime import datetime, time
from pathlib import Path

from focusguard.config import Config
from focusguard.nft import NFT_RULES, write_dnsmasq_config
from focusguard.schedule import is_allowed, schedule_state


def test_focus_mode_emits_block_rules_and_preserves_whitelist():
    """Focus mode emits blocks without covering a whitelisted child domain."""
    cfg = Config()
    assert "x.com" in cfg.blocklist
    assert "youtube.com" in cfg.blocklist
    assert "googlevideo.com" in cfg.blocklist
    assert "ytimg.com" in cfg.blocklist
    assert "music.youtube.com" in cfg.whitelist

    # focus time outside allow window
    focus_now = datetime(2026, 1, 1, 23, 0)
    start, end = time(15, 0), time(22, 0)
    assert not is_allowed(focus_now, start, end)
    state = schedule_state(focus_now, start, end)
    assert not state.allowed

    with tempfile.TemporaryDirectory() as td:
        p = Path(td) / "dnsmasq-focus.conf"
        write_dnsmasq_config(p, cfg, enabled=True)  # focus => enabled
        content = p.read_text()
        assert (
            "nftset=/x.com/4#inet#focusguard#blocked_v4,6#inet#focusguard#blocked_v6"
            in content
        )
        # The parent rule would also classify music.youtube.com, so it is omitted.
        assert "nftset=/youtube.com/" not in content
        # Explicit siblings remain blocked.
        assert "nftset=/www.youtube.com/" in content
        assert (
            "nftset=/googlevideo.com/4#inet#focusguard#blocked_v4,6#inet#focusguard#blocked_v6"
            in content
        )
        assert (
            "nftset=/ytimg.com/4#inet#focusguard#blocked_v4,6#inet#focusguard#blocked_v6"
            in content
        )
        assert "music.youtube.com" not in content
        assert (
            "nftset=/reddit.com/4#inet#focusguard#blocked_v4,6#inet#focusguard#blocked_v6"
            in content
        )


def test_whitelisted_child_suppresses_overlapping_parent_rule():
    cfg = Config(
        blocklist=("example.com",),
        whitelist=("allowed.example.com",),
    )

    with tempfile.TemporaryDirectory() as td:
        path = Path(td) / "dnsmasq-focus.conf"
        write_dnsmasq_config(path, cfg, enabled=True)
        assert "nftset=/example.com/" not in path.read_text(encoding="utf-8")


def test_free_mode_emits_no_blocks():
    cfg = Config()
    free_now = datetime(2026, 1, 1, 16, 0)
    start, end = time(15, 0), time(22, 0)
    assert is_allowed(free_now, start, end)

    with tempfile.TemporaryDirectory() as td:
        p = Path(td) / "dnsmasq-free.conf"
        write_dnsmasq_config(p, cfg, enabled=False)
        content = p.read_text()
        assert "ipset=" not in content
        assert "nftset=" not in content
        assert content.strip().endswith(
            "# Generated by FocusGuard. Do not edit while focusguard is running."
        )


def test_nft_rules_have_reject_for_blocked_sets():
    assert "blocked_v4" in NFT_RULES
    assert "blocked_v6" in NFT_RULES
    assert "tcp dport { 80, 443 } reject" in NFT_RULES
    assert "udp dport 443 reject" in NFT_RULES
    assert "ip daddr @blocked_v4" in NFT_RULES
    assert "ip6 daddr @blocked_v6" in NFT_RULES
