"""nftables and dnsmasq integration."""

from __future__ import annotations

import subprocess
from pathlib import Path

from .config import Config

NFT_RULES = """table inet focusguard {
  set blocked_v4 { type ipv4_addr; flags interval; }
  set blocked_v6 { type ipv6_addr; flags interval; }
  chain output {
    type filter hook output priority 0; policy accept;
    ip daddr @blocked_v4 tcp dport { 80, 443 } reject
    ip6 daddr @blocked_v6 tcp dport { 80, 443 } reject
  }
}
"""


def run(command: list[str]) -> subprocess.CompletedProcess[str]:
    """Run a command with captured text output."""
    return subprocess.run(command, check=False, text=True, capture_output=True)


def install_nft_rules(path: Path) -> None:
    """Install and apply FocusGuard nftables table."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(NFT_RULES, encoding="utf-8")
    run(["nft", "delete", "table", "inet", "focusguard"])
    result = run(["nft", "-f", str(path)])
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "failed to apply nftables rules")


def disable_nft_rules() -> None:
    """Remove FocusGuard nftables table."""
    run(["nft", "delete", "table", "inet", "focusguard"])


def write_dnsmasq_config(path: Path, config: Config, enabled: bool) -> None:
    """Write NetworkManager dnsmasq ipset rules for blocked domains."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by FocusGuard. Do not edit while focusguard is running.\n"]
    if enabled:
        blocked = [d for d in config.blocklist if d not in config.whitelist]
        for domain in blocked:
            clean = domain.removeprefix("*.")
            lines.append(f"ipset=/{clean}/blocked_v4,blocked_v6\n")
    path.write_text("".join(lines), encoding="utf-8")
